### ISSUE TITLE
How long do you think it would take to replace the existing qm js library with a swagger generated one?

### ISSUE THREAD

**Issue by mikepsinn** [QuantiModo/QuantiModo-WordPress-Plugin#104]
https://github.com/swagger-api/swagger-js

**Comment by megarocks** [comment]
I think 12 - 18 hours

**Comment by mikepsinn** [comment]
That's a long time. I guess we should backlog this.

On Mon, Oct 5, 2015, 10:43 AM Vitaly <notifications@github.com> wrote:

> Assigned #104
> <https://github.com/Abolitionist-Project/QuantiModo-WordPress-Plugin/issues/104>
> to @mikepsinn <https://github.com/mikepsinn>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abolitionist-Project/QuantiModo-WordPress-Plugin/issues/104#event-426938187>
> .
>

--
